package com.grotek.pojo;

import java.util.Date;
import java.util.List;

public class ApplyForSend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_for_send.id
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_for_send.did
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_for_send.dcompany
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    private String dcompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_for_send.address
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_for_send.phone
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_for_send.contact
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_for_send.eid
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    private Employee employee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_for_send.date
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_for_send.opstatus
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    private Integer opstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply_for_send.status
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    private Integer status;
    
    private Double total;
    
    private List<ProductboxApItem> boxitems;
    
    private List<ProductPageApItem> pageitems;
    
    private List<ProductPackApItem> packitems;
    
    private List<SampleApItem> sampleitems;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_for_send.id
     *
     * @return the value of apply_for_send.id
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_for_send.id
     *
     * @param id the value for apply_for_send.id
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_for_send.dcompany
     *
     * @return the value of apply_for_send.dcompany
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public String getDcompany() {
        return dcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_for_send.dcompany
     *
     * @param dcompany the value for apply_for_send.dcompany
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public void setDcompany(String dcompany) {
        this.dcompany = dcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_for_send.address
     *
     * @return the value of apply_for_send.address
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_for_send.address
     *
     * @param address the value for apply_for_send.address
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_for_send.phone
     *
     * @return the value of apply_for_send.phone
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_for_send.phone
     *
     * @param phone the value for apply_for_send.phone
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_for_send.contact
     *
     * @return the value of apply_for_send.contact
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_for_send.contact
     *
     * @param contact the value for apply_for_send.contact
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_for_send.date
     *
     * @return the value of apply_for_send.date
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_for_send.date
     *
     * @param date the value for apply_for_send.date
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_for_send.opstatus
     *
     * @return the value of apply_for_send.opstatus
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public Integer getOpstatus() {
        return opstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_for_send.opstatus
     *
     * @param opstatus the value for apply_for_send.opstatus
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public void setOpstatus(Integer opstatus) {
        this.opstatus = opstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply_for_send.status
     *
     * @return the value of apply_for_send.status
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply_for_send.status
     *
     * @param status the value for apply_for_send.status
     *
     * @mbggenerated Thu Jul 21 10:21:31 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public List<ProductboxApItem> getBoxitems() {
		return boxitems;
	}

	public void setBoxitems(List<ProductboxApItem> boxitems) {
		this.boxitems = boxitems;
	}

	public List<ProductPageApItem> getPageitems() {
		return pageitems;
	}

	public void setPageitems(List<ProductPageApItem> pageitems) {
		this.pageitems = pageitems;
	}

	public List<ProductPackApItem> getPackitems() {
		return packitems;
	}

	public void setPackitems(List<ProductPackApItem> packitems) {
		this.packitems = packitems;
	}

	public Double getTotal() {
		return total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public List<SampleApItem> getSampleitems() {
		return sampleitems;
	}

	public void setSampleitems(List<SampleApItem> sampleitems) {
		this.sampleitems = sampleitems;
	}
    
    
}