package com.grotek.pojo;

import java.util.Date;

public class DealerValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_value.id
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_value.did
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_value.promote
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    private Double promote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_value.rebate
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    private Double rebate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_value.reward
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    private Double reward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_value.gift
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    private Double gift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_value.description
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_value.date
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_value.status
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_value.id
     *
     * @return the value of dealer_value.id
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_value.id
     *
     * @param id the value for dealer_value.id
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_value.promote
     *
     * @return the value of dealer_value.promote
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public Double getPromote() {
        return promote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_value.promote
     *
     * @param promote the value for dealer_value.promote
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public void setPromote(Double promote) {
        this.promote = promote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_value.rebate
     *
     * @return the value of dealer_value.rebate
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public Double getRebate() {
        return rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_value.rebate
     *
     * @param rebate the value for dealer_value.rebate
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public void setRebate(Double rebate) {
        this.rebate = rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_value.reward
     *
     * @return the value of dealer_value.reward
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public Double getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_value.reward
     *
     * @param reward the value for dealer_value.reward
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public void setReward(Double reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_value.gift
     *
     * @return the value of dealer_value.gift
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public Double getGift() {
        return gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_value.gift
     *
     * @param gift the value for dealer_value.gift
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public void setGift(Double gift) {
        this.gift = gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_value.description
     *
     * @return the value of dealer_value.description
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_value.description
     *
     * @param description the value for dealer_value.description
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_value.date
     *
     * @return the value of dealer_value.date
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_value.date
     *
     * @param date the value for dealer_value.date
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_value.status
     *
     * @return the value of dealer_value.status
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_value.status
     *
     * @param status the value for dealer_value.status
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}
    
}