package com.grotek.pojo;

import java.util.Date;

public class DealerPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_price.id
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_price.did
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_price.pid
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    private ProductBox box;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_price.price
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_price.status
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_price.date
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_price.id
     *
     * @return the value of dealer_price.id
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_price.id
     *
     * @param id the value for dealer_price.id
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_price.price
     *
     * @return the value of dealer_price.price
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_price.price
     *
     * @param price the value for dealer_price.price
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_price.status
     *
     * @return the value of dealer_price.status
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_price.status
     *
     * @param status the value for dealer_price.status
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_price.date
     *
     * @return the value of dealer_price.date
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_price.date
     *
     * @param date the value for dealer_price.date
     *
     * @mbggenerated Wed Jul 13 10:21:37 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	public ProductBox getBox() {
		return box;
	}

	public void setBox(ProductBox box) {
		this.box = box;
	}
    
}