package com.grotek.pojo;

import java.util.Date;

public class DealerCreditDic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_credit_dic.id
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_credit_dic.stid
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    private ShopTypeDic type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_credit_dic.objective
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    private String objective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_credit_dic.rebate
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    private Double rebate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_credit_dic.credit
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    private Double credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_credit_dic.description
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_credit_dic.status
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    private Integer status;
    
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_credit_dic.id
     *
     * @return the value of dealer_credit_dic.id
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_credit_dic.id
     *
     * @param id the value for dealer_credit_dic.id
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_credit_dic.objective
     *
     * @return the value of dealer_credit_dic.objective
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public String getObjective() {
        return objective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_credit_dic.objective
     *
     * @param objective the value for dealer_credit_dic.objective
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public void setObjective(String objective) {
        this.objective = objective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_credit_dic.rebate
     *
     * @return the value of dealer_credit_dic.rebate
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public Double getRebate() {
        return rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_credit_dic.rebate
     *
     * @param rebate the value for dealer_credit_dic.rebate
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public void setRebate(Double rebate) {
        this.rebate = rebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_credit_dic.credit
     *
     * @return the value of dealer_credit_dic.credit
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public Double getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_credit_dic.credit
     *
     * @param credit the value for dealer_credit_dic.credit
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public void setCredit(Double credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_credit_dic.description
     *
     * @return the value of dealer_credit_dic.description
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_credit_dic.description
     *
     * @param description the value for dealer_credit_dic.description
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_credit_dic.status
     *
     * @return the value of dealer_credit_dic.status
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_credit_dic.status
     *
     * @param status the value for dealer_credit_dic.status
     *
     * @mbggenerated Fri Jun 10 13:50:57 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ShopTypeDic getType() {
		return type;
	}

	public void setType(ShopTypeDic type) {
		this.type = type;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
    
}