package com.grotek.pojo;

import java.util.Date;

public class DealerSale {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.id
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.did
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.bid
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private ProductBox box;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.price
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.count
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.total
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.ordertime
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private Date ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.posttime
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private Date posttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.paystatus
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private String paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.amountpaid
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private Double amountpaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.status
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dealer_sales.outid
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    private Integer outid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_sales.id
     *
     * @return the value of dealer_sales.id
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_sales.id
     *
     * @param id the value for dealer_sales.id
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_sales.price
     *
     * @return the value of dealer_sales.price
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_sales.price
     *
     * @param price the value for dealer_sales.price
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_sales.count
     *
     * @return the value of dealer_sales.count
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_sales.count
     *
     * @param count the value for dealer_sales.count
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_sales.total
     *
     * @return the value of dealer_sales.total
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_sales.total
     *
     * @param total the value for dealer_sales.total
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_sales.ordertime
     *
     * @return the value of dealer_sales.ordertime
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_sales.ordertime
     *
     * @param ordertime the value for dealer_sales.ordertime
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_sales.posttime
     *
     * @return the value of dealer_sales.posttime
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public Date getPosttime() {
        return posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_sales.posttime
     *
     * @param posttime the value for dealer_sales.posttime
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public void setPosttime(Date posttime) {
        this.posttime = posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_sales.paystatus
     *
     * @return the value of dealer_sales.paystatus
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public String getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_sales.paystatus
     *
     * @param paystatus the value for dealer_sales.paystatus
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public void setPaystatus(String paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_sales.amountpaid
     *
     * @return the value of dealer_sales.amountpaid
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public Double getAmountpaid() {
        return amountpaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_sales.amountpaid
     *
     * @param amountpaid the value for dealer_sales.amountpaid
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public void setAmountpaid(Double amountpaid) {
        this.amountpaid = amountpaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_sales.status
     *
     * @return the value of dealer_sales.status
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_sales.status
     *
     * @param status the value for dealer_sales.status
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dealer_sales.outid
     *
     * @return the value of dealer_sales.outid
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public Integer getOutid() {
        return outid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dealer_sales.outid
     *
     * @param outid the value for dealer_sales.outid
     *
     * @mbggenerated Fri Jul 08 09:25:08 CST 2016
     */
    public void setOutid(Integer outid) {
        this.outid = outid;
    }

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	public ProductBox getBox() {
		return box;
	}

	public void setBox(ProductBox box) {
		this.box = box;
	}
    
    
}