package com.grotek.pojo;

import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

public class DeliveryOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.id
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.pay_name
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.pay_address
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String payAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.pay_contact
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String payContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.pay_phone
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String payPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.receive_name
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String receiveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.receive_address
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String receiveAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.receive_contact
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String receiveContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.receive_phone
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String receivePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.eid
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private Employee employee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.date
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.phone
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.mobile
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.did
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.gdnum
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String gdnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.htnum
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private String htnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.aid
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delivery_order.status
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    private Integer status;
    
    private List<ProductboxApItem> boxitems;
    
    private List<ProductPageApItem> pageitems;
    
    private List<ProductPackApItem> packitems;
    
    private List<SampleApItem> sampleitems;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.id
     *
     * @return the value of delivery_order.id
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.id
     *
     * @param id the value for delivery_order.id
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.pay_name
     *
     * @return the value of delivery_order.pay_name
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.pay_name
     *
     * @param payName the value for delivery_order.pay_name
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setPayName(String payName) {
        this.payName = payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.pay_address
     *
     * @return the value of delivery_order.pay_address
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getPayAddress() {
        return payAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.pay_address
     *
     * @param payAddress the value for delivery_order.pay_address
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setPayAddress(String payAddress) {
        this.payAddress = payAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.pay_contact
     *
     * @return the value of delivery_order.pay_contact
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getPayContact() {
        return payContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.pay_contact
     *
     * @param payContact the value for delivery_order.pay_contact
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setPayContact(String payContact) {
        this.payContact = payContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.pay_phone
     *
     * @return the value of delivery_order.pay_phone
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getPayPhone() {
        return payPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.pay_phone
     *
     * @param payPhone the value for delivery_order.pay_phone
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setPayPhone(String payPhone) {
        this.payPhone = payPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.receive_name
     *
     * @return the value of delivery_order.receive_name
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getReceiveName() {
        return receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.receive_name
     *
     * @param receiveName the value for delivery_order.receive_name
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setReceiveName(String receiveName) {
        this.receiveName = receiveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.receive_address
     *
     * @return the value of delivery_order.receive_address
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getReceiveAddress() {
        return receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.receive_address
     *
     * @param receiveAddress the value for delivery_order.receive_address
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setReceiveAddress(String receiveAddress) {
        this.receiveAddress = receiveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.receive_contact
     *
     * @return the value of delivery_order.receive_contact
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getReceiveContact() {
        return receiveContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.receive_contact
     *
     * @param receiveContact the value for delivery_order.receive_contact
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setReceiveContact(String receiveContact) {
        this.receiveContact = receiveContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.receive_phone
     *
     * @return the value of delivery_order.receive_phone
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getReceivePhone() {
        return receivePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.receive_phone
     *
     * @param receivePhone the value for delivery_order.receive_phone
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setReceivePhone(String receivePhone) {
        this.receivePhone = receivePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.date
     *
     * @return the value of delivery_order.date
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.date
     *
     * @param date the value for delivery_order.date
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.phone
     *
     * @return the value of delivery_order.phone
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.phone
     *
     * @param phone the value for delivery_order.phone
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.mobile
     *
     * @return the value of delivery_order.mobile
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.mobile
     *
     * @param mobile the value for delivery_order.mobile
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.gdnum
     *
     * @return the value of delivery_order.gdnum
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getGdnum() {
        return gdnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.gdnum
     *
     * @param gdnum the value for delivery_order.gdnum
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setGdnum(String gdnum) {
        this.gdnum = gdnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.htnum
     *
     * @return the value of delivery_order.htnum
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public String getHtnum() {
        return htnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.htnum
     *
     * @param htnum the value for delivery_order.htnum
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setHtnum(String htnum) {
        this.htnum = htnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.aid
     *
     * @return the value of delivery_order.aid
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.aid
     *
     * @param aid the value for delivery_order.aid
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column delivery_order.status
     *
     * @return the value of delivery_order.status
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column delivery_order.status
     *
     * @param status the value for delivery_order.status
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	public List<ProductboxApItem> getBoxitems() {
		return boxitems;
	}

	public void setBoxitems(List<ProductboxApItem> boxitems) {
		this.boxitems = boxitems;
	}

	public List<ProductPageApItem> getPageitems() {
		return pageitems;
	}

	public void setPageitems(List<ProductPageApItem> pageitems) {
		this.pageitems = pageitems;
	}

	public List<ProductPackApItem> getPackitems() {
		return packitems;
	}

	public void setPackitems(List<ProductPackApItem> packitems) {
		this.packitems = packitems;
	}

	public List<SampleApItem> getSampleitems() {
		return sampleitems;
	}

	public void setSampleitems(List<SampleApItem> sampleitems) {
		this.sampleitems = sampleitems;
	}
    
    
}