package com.grotek.pojo;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.fullname
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.code
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.sex
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.address
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.mobile
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.postcode
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.phone
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.position
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private PositionDic position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.superior
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String superior;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.dept
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private DepartmentDic dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.headimg
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String headimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.password
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.regform
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private String regform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.status
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    private Integer status;
    
    private String sname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.fullname
     *
     * @return the value of employee.fullname
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.fullname
     *
     * @param fullname the value for employee.fullname
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.code
     *
     * @return the value of employee.code
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.code
     *
     * @param code the value for employee.code
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.sex
     *
     * @return the value of employee.sex
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.sex
     *
     * @param sex the value for employee.sex
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.address
     *
     * @return the value of employee.address
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.address
     *
     * @param address the value for employee.address
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.mobile
     *
     * @return the value of employee.mobile
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.mobile
     *
     * @param mobile the value for employee.mobile
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.postcode
     *
     * @return the value of employee.postcode
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.postcode
     *
     * @param postcode the value for employee.postcode
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.phone
     *
     * @return the value of employee.phone
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.phone
     *
     * @param phone the value for employee.phone
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.position
     *
     * @return the value of employee.position
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public PositionDic getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.position
     *
     * @param position the value for employee.position
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setPosition(PositionDic position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.superior
     *
     * @return the value of employee.superior
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getSuperior() {
        return superior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.superior
     *
     * @param superior the value for employee.superior
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setSuperior(String superior) {
        this.superior = superior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.dept
     *
     * @return the value of employee.dept
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public DepartmentDic getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.dept
     *
     * @param dept the value for employee.dept
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setDept(DepartmentDic dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.headimg
     *
     * @return the value of employee.headimg
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.headimg
     *
     * @param headimg the value for employee.headimg
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.password
     *
     * @return the value of employee.password
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.password
     *
     * @param password the value for employee.password
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.regform
     *
     * @return the value of employee.regform
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public String getRegform() {
        return regform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.regform
     *
     * @param regform the value for employee.regform
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setRegform(String regform) {
        this.regform = regform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.status
     *
     * @return the value of employee.status
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.status
     *
     * @param status the value for employee.status
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public String getSname() {
		return sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}
    
}