package com.grotek.pojo;

import java.util.Date;

public class EmployeeProm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_promote.id
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_promote.eid
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    private Employee employee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_promote.position
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    private PositionDic position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_promote.superior
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    private String superior;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_promote.evaluate
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    private String evaluate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_promote.date
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_promote.status
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_promote.id
     *
     * @return the value of employee_promote.id
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_promote.id
     *
     * @param id the value for employee_promote.id
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_promote.position
     *
     * @return the value of employee_promote.position
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public PositionDic getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_promote.position
     *
     * @param position the value for employee_promote.position
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public void setPosition(PositionDic position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_promote.superior
     *
     * @return the value of employee_promote.superior
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public String getSuperior() {
        return superior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_promote.superior
     *
     * @param superior the value for employee_promote.superior
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public void setSuperior(String superior) {
        this.superior = superior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_promote.evaluate
     *
     * @return the value of employee_promote.evaluate
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public String getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_promote.evaluate
     *
     * @param evaluate the value for employee_promote.evaluate
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public void setEvaluate(String evaluate) {
        this.evaluate = evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_promote.date
     *
     * @return the value of employee_promote.date
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_promote.date
     *
     * @param date the value for employee_promote.date
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_promote.status
     *
     * @return the value of employee_promote.status
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_promote.status
     *
     * @param status the value for employee_promote.status
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}
    
}