package com.grotek.pojo;

import java.util.Date;

public class EmployeeGasoline {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_gasoline.id
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_gasoline.eid
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    private Employee employee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_gasoline.exs
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    private Double exs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_gasoline.date
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_gasoline.status
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_gasoline.id
     *
     * @return the value of employee_gasoline.id
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_gasoline.id
     *
     * @param id the value for employee_gasoline.id
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_gasoline.exs
     *
     * @return the value of employee_gasoline.exs
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    public Double getExs() {
        return exs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_gasoline.exs
     *
     * @param exs the value for employee_gasoline.exs
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    public void setExs(Double exs) {
        this.exs = exs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_gasoline.date
     *
     * @return the value of employee_gasoline.date
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_gasoline.date
     *
     * @param date the value for employee_gasoline.date
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_gasoline.status
     *
     * @return the value of employee_gasoline.status
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_gasoline.status
     *
     * @param status the value for employee_gasoline.status
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}
    
}