package com.grotek.pojo;

import java.util.Date;

public class EmployeeReward {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_reward.id
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_reward.eid
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    private Employee employee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_reward.date
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_reward.status
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_reward.item
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    private String item;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_reward.amount
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_reward.description
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_reward.id
     *
     * @return the value of employee_reward.id
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_reward.id
     *
     * @param id the value for employee_reward.id
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_reward.date
     *
     * @return the value of employee_reward.date
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_reward.date
     *
     * @param date the value for employee_reward.date
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_reward.status
     *
     * @return the value of employee_reward.status
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_reward.status
     *
     * @param status the value for employee_reward.status
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_reward.item
     *
     * @return the value of employee_reward.item
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_reward.item
     *
     * @param item the value for employee_reward.item
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public void setItem(String item) {
        this.item = item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_reward.amount
     *
     * @return the value of employee_reward.amount
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_reward.amount
     *
     * @param amount the value for employee_reward.amount
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_reward.description
     *
     * @return the value of employee_reward.description
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_reward.description
     *
     * @param description the value for employee_reward.description
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}
    
    
}