package com.grotek.pojo;

import java.util.Date;
import java.util.List;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.springframework.format.annotation.DateTimeFormat;

@JsonIgnoreProperties(ignoreUnknown=true)
public class ExsRbsm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm.id
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm.did
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm.stid
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    private JobtypeDic type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm.sum
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    private Double sum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm.remarks
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm.date
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm.eid
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    private Employee employee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm.checked
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    private Integer checked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm.paystatus
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    private Integer paystatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm.status
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    private Integer status;
    
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date riqi;
    
    private List<ExsRbsmItem> items;
    
    private int count;
    
    private String des;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm.id
     *
     * @return the value of exs_rbsm.id
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm.id
     *
     * @param id the value for exs_rbsm.id
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm.sum
     *
     * @return the value of exs_rbsm.sum
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public Double getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm.sum
     *
     * @param sum the value for exs_rbsm.sum
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public void setSum(Double sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm.remarks
     *
     * @return the value of exs_rbsm.remarks
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm.remarks
     *
     * @param remarks the value for exs_rbsm.remarks
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm.date
     *
     * @return the value of exs_rbsm.date
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm.date
     *
     * @param date the value for exs_rbsm.date
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm.checked
     *
     * @return the value of exs_rbsm.checked
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public Integer getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm.checked
     *
     * @param checked the value for exs_rbsm.checked
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public void setChecked(Integer checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm.paystatus
     *
     * @return the value of exs_rbsm.paystatus
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public Integer getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm.paystatus
     *
     * @param paystatus the value for exs_rbsm.paystatus
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public void setPaystatus(Integer paystatus) {
        this.paystatus = paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm.status
     *
     * @return the value of exs_rbsm.status
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm.status
     *
     * @param status the value for exs_rbsm.status
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	public JobtypeDic getType() {
		return type;
	}

	public void setType(JobtypeDic type) {
		this.type = type;
	}

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Date getRiqi() {
		return riqi;
	}

	public void setRiqi(Date riqi) {
		this.riqi = riqi;
	}

	public List<ExsRbsmItem> getItems() {
		return items;
	}

	public void setItems(List<ExsRbsmItem> items) {
		this.items = items;
	}

	public int getCount() {
		return items==null?0:items.size();
	}

	public void setCount(int count) {
		this.count = count;
	}

	public String getDes() {
		return des;
	}

	public void setDes(String des) {
		this.des = des;
	}	
    
}