package com.grotek.pojo;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class ExsRbsmItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm_item.id
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm_item.pid
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm_item.tid
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    private ExsType type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm_item.eid
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    private String eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm_item.amount
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm_item.date
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_rbsm_item.status
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm_item.id
     *
     * @return the value of exs_rbsm_item.id
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm_item.id
     *
     * @param id the value for exs_rbsm_item.id
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm_item.pid
     *
     * @return the value of exs_rbsm_item.pid
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm_item.pid
     *
     * @param pid the value for exs_rbsm_item.pid
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm_item.eid
     *
     * @return the value of exs_rbsm_item.eid
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm_item.eid
     *
     * @param eid the value for exs_rbsm_item.eid
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public void setEid(String eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm_item.amount
     *
     * @return the value of exs_rbsm_item.amount
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm_item.amount
     *
     * @param amount the value for exs_rbsm_item.amount
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm_item.date
     *
     * @return the value of exs_rbsm_item.date
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm_item.date
     *
     * @param date the value for exs_rbsm_item.date
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_rbsm_item.status
     *
     * @return the value of exs_rbsm_item.status
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_rbsm_item.status
     *
     * @param status the value for exs_rbsm_item.status
     *
     * @mbggenerated Mon Aug 22 10:10:07 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ExsType getType() {
		return type;
	}

	public void setType(ExsType type) {
		this.type = type;
	}
    
}