package com.grotek.pojo;

public class ExsType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_type.id
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_type.name
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_type.label
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exs_type.status
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_type.id
     *
     * @return the value of exs_type.id
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_type.id
     *
     * @param id the value for exs_type.id
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_type.name
     *
     * @return the value of exs_type.name
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_type.name
     *
     * @param name the value for exs_type.name
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_type.label
     *
     * @return the value of exs_type.label
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_type.label
     *
     * @param label the value for exs_type.label
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exs_type.status
     *
     * @return the value of exs_type.status
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exs_type.status
     *
     * @param status the value for exs_type.status
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}