package com.grotek.pojo;

public class GrotekUnit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.id
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.name
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.status
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.id
     *
     * @return the value of unit.id
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.id
     *
     * @param id the value for unit.id
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.name
     *
     * @return the value of unit.name
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.name
     *
     * @param name the value for unit.name
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.status
     *
     * @return the value of unit.status
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.status
     *
     * @param status the value for unit.status
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}