package com.grotek.pojo;

public class InSchemeRaws {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_scheme_raws.id
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_scheme_raws.sid
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_scheme_raws.rid
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    private ProductRaw raw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_scheme_raws.count
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    private Double count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_scheme_raws.status
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_scheme_raws.id
     *
     * @return the value of in_scheme_raws.id
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_scheme_raws.id
     *
     * @param id the value for in_scheme_raws.id
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_scheme_raws.sid
     *
     * @return the value of in_scheme_raws.sid
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_scheme_raws.sid
     *
     * @param sid the value for in_scheme_raws.sid
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_scheme_raws.count
     *
     * @return the value of in_scheme_raws.count
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    public Double getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_scheme_raws.count
     *
     * @param count the value for in_scheme_raws.count
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    public void setCount(Double count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_scheme_raws.status
     *
     * @return the value of in_scheme_raws.status
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_scheme_raws.status
     *
     * @param status the value for in_scheme_raws.status
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductRaw getRaw() {
		return raw;
	}

	public void setRaw(ProductRaw raw) {
		this.raw = raw;
	}
    
    
}