package com.grotek.pojo;

public class ManureType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manure_type.id
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manure_type.name
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manure_type.status
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manure_type.id
     *
     * @return the value of manure_type.id
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manure_type.id
     *
     * @param id the value for manure_type.id
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manure_type.name
     *
     * @return the value of manure_type.name
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manure_type.name
     *
     * @param name the value for manure_type.name
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manure_type.status
     *
     * @return the value of manure_type.status
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manure_type.status
     *
     * @param status the value for manure_type.status
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}