package com.grotek.pojo;

import java.util.Date;

public class MonthlyIncome {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_income.id
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_income.eid
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    private Employee employee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_income.date
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_income.wages
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    private Double wages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_income.divident
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    private Double divident;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_income.allowance
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    private Double allowance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_income.travel
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    private Double travel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_income.award
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    private Double award;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_income.costhour
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    private Double costhour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthly_income.status
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_income.id
     *
     * @return the value of monthly_income.id
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_income.id
     *
     * @param id the value for monthly_income.id
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_income.date
     *
     * @return the value of monthly_income.date
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_income.date
     *
     * @param date the value for monthly_income.date
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_income.wages
     *
     * @return the value of monthly_income.wages
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public Double getWages() {
        return wages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_income.wages
     *
     * @param wages the value for monthly_income.wages
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public void setWages(Double wages) {
        this.wages = wages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_income.divident
     *
     * @return the value of monthly_income.divident
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public Double getDivident() {
        return divident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_income.divident
     *
     * @param divident the value for monthly_income.divident
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public void setDivident(Double divident) {
        this.divident = divident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_income.allowance
     *
     * @return the value of monthly_income.allowance
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public Double getAllowance() {
        return allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_income.allowance
     *
     * @param allowance the value for monthly_income.allowance
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public void setAllowance(Double allowance) {
        this.allowance = allowance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_income.travel
     *
     * @return the value of monthly_income.travel
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public Double getTravel() {
        return travel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_income.travel
     *
     * @param travel the value for monthly_income.travel
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public void setTravel(Double travel) {
        this.travel = travel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_income.award
     *
     * @return the value of monthly_income.award
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public Double getAward() {
        return award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_income.award
     *
     * @param award the value for monthly_income.award
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public void setAward(Double award) {
        this.award = award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_income.costhour
     *
     * @return the value of monthly_income.costhour
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public Double getCosthour() {
        return costhour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_income.costhour
     *
     * @param costhour the value for monthly_income.costhour
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public void setCosthour(Double costhour) {
        this.costhour = costhour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthly_income.status
     *
     * @return the value of monthly_income.status
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthly_income.status
     *
     * @param status the value for monthly_income.status
     *
     * @mbggenerated Tue Aug 02 13:49:41 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}
    
    
}