package com.grotek.pojo;

import java.util.Date;

public class PositionDic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_dic.id
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_dic.name
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_dic.objective
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private String objective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_dic.amortization
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Double amortization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_dic.salary
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Double salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_dic.travel_allow
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Double travelAllow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_dic.mobile_allow
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Double mobileAllow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_dic.description
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_dic.date
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_dic.status
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Integer status;
    
    private Double costhour;
    
    private Integer salestargets;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_dic.id
     *
     * @return the value of position_dic.id
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_dic.id
     *
     * @param id the value for position_dic.id
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_dic.name
     *
     * @return the value of position_dic.name
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_dic.name
     *
     * @param name the value for position_dic.name
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_dic.objective
     *
     * @return the value of position_dic.objective
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public String getObjective() {
        return objective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_dic.objective
     *
     * @param objective the value for position_dic.objective
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setObjective(String objective) {
        this.objective = objective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_dic.amortization
     *
     * @return the value of position_dic.amortization
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Double getAmortization() {
        return amortization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_dic.amortization
     *
     * @param amortization the value for position_dic.amortization
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setAmortization(Double amortization) {
        this.amortization = amortization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_dic.salary
     *
     * @return the value of position_dic.salary
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_dic.salary
     *
     * @param salary the value for position_dic.salary
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_dic.travel_allow
     *
     * @return the value of position_dic.travel_allow
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Double getTravelAllow() {
        return travelAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_dic.travel_allow
     *
     * @param travelAllow the value for position_dic.travel_allow
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setTravelAllow(Double travelAllow) {
        this.travelAllow = travelAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_dic.mobile_allow
     *
     * @return the value of position_dic.mobile_allow
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Double getMobileAllow() {
        return mobileAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_dic.mobile_allow
     *
     * @param mobileAllow the value for position_dic.mobile_allow
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setMobileAllow(Double mobileAllow) {
        this.mobileAllow = mobileAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_dic.description
     *
     * @return the value of position_dic.description
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_dic.description
     *
     * @param description the value for position_dic.description
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_dic.date
     *
     * @return the value of position_dic.date
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_dic.date
     *
     * @param date the value for position_dic.date
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_dic.status
     *
     * @return the value of position_dic.status
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_dic.status
     *
     * @param status the value for position_dic.status
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Double getCosthour() {
		return costhour;
	}

	public void setCosthour(Double costhour) {
		this.costhour = costhour;
	}

	public Integer getSalestargets() {
		return salestargets;
	}

	public void setSalestargets(Integer salestargets) {
		this.salestargets = salestargets;
	}
    
}