package com.grotek.pojo;

import java.util.Date;

public class ProductPage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpageinfo.id
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpageinfo.code
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpageinfo.name
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpageinfo.tid
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    private PageType type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpageinfo.price
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpageinfo.date
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpageinfo.status
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpageinfo.id
     *
     * @return the value of productpageinfo.id
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpageinfo.id
     *
     * @param id the value for productpageinfo.id
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpageinfo.code
     *
     * @return the value of productpageinfo.code
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpageinfo.code
     *
     * @param code the value for productpageinfo.code
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpageinfo.name
     *
     * @return the value of productpageinfo.name
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpageinfo.name
     *
     * @param name the value for productpageinfo.name
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpageinfo.price
     *
     * @return the value of productpageinfo.price
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpageinfo.price
     *
     * @param price the value for productpageinfo.price
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpageinfo.date
     *
     * @return the value of productpageinfo.date
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpageinfo.date
     *
     * @param date the value for productpageinfo.date
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpageinfo.status
     *
     * @return the value of productpageinfo.status
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpageinfo.status
     *
     * @param status the value for productpageinfo.status
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public PageType getType() {
		return type;
	}

	public void setType(PageType type) {
		this.type = type;
	}
    
}