package com.grotek.pojo;

import java.util.Date;

public class ProductLabor_Cost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_cost.id
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_cost.pid
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    private ProductBox box;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_cost.pielabor_price
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    private Double pielaborPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_cost.tonlabor_price
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    private Double tonlaborPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_cost.status
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    private Integer status;
    
    private Date date;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlabor_cost.id
     *
     * @return the value of productlabor_cost.id
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlabor_cost.id
     *
     * @param id the value for productlabor_cost.id
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlabor_cost.pielabor_price
     *
     * @return the value of productlabor_cost.pielabor_price
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    public Double getPielaborPrice() {
        return pielaborPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlabor_cost.pielabor_price
     *
     * @param pielaborPrice the value for productlabor_cost.pielabor_price
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    public void setPielaborPrice(Double pielaborPrice) {
        this.pielaborPrice = pielaborPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlabor_cost.tonlabor_price
     *
     * @return the value of productlabor_cost.tonlabor_price
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    public Double getTonlaborPrice() {
        return tonlaborPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlabor_cost.tonlabor_price
     *
     * @param tonlaborPrice the value for productlabor_cost.tonlabor_price
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    public void setTonlaborPrice(Double tonlaborPrice) {
        this.tonlaborPrice = tonlaborPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlabor_cost.status
     *
     * @return the value of productlabor_cost.status
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlabor_cost.status
     *
     * @param status the value for productlabor_cost.status
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductBox getBox() {
		return box;
	}

	public void setBox(ProductBox box) {
		this.box = box;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
    
    
}