package com.grotek.pojo;

import java.util.Date;

public class ProductRaw_Out {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productraw_out.id
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productraw_out.pid
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    private ProductRaw productRaw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productraw_out.date
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productraw_out.count
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    private Double count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productraw_out.did
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productraw_out.status
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    private Integer status;
    
    private Integer boxinid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productraw_out.id
     *
     * @return the value of productraw_out.id
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productraw_out.id
     *
     * @param id the value for productraw_out.id
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productraw_out.date
     *
     * @return the value of productraw_out.date
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productraw_out.date
     *
     * @param date the value for productraw_out.date
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productraw_out.count
     *
     * @return the value of productraw_out.count
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    public Double getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productraw_out.count
     *
     * @param count the value for productraw_out.count
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    public void setCount(Double count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productraw_out.status
     *
     * @return the value of productraw_out.status
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productraw_out.status
     *
     * @param status the value for productraw_out.status
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductRaw getProductRaw() {
		return productRaw;
	}

	public void setProductRaw(ProductRaw productRaw) {
		this.productRaw = productRaw;
	}

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	public Integer getBoxinid() {
		return boxinid;
	}

	public void setBoxinid(Integer boxinid) {
		this.boxinid = boxinid;
	}
    
}