package com.grotek.pojo;

import java.util.Date;

public class ProductPage_In {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpage_in.id
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpage_in.pid
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    private ProductPage page;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpage_in.date
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpage_in.count
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpage_in.did
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpage_in.status
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpage_in.id
     *
     * @return the value of productpage_in.id
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpage_in.id
     *
     * @param id the value for productpage_in.id
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpage_in.date
     *
     * @return the value of productpage_in.date
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpage_in.date
     *
     * @param date the value for productpage_in.date
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpage_in.count
     *
     * @return the value of productpage_in.count
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpage_in.count
     *
     * @param count the value for productpage_in.count
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpage_in.status
     *
     * @return the value of productpage_in.status
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpage_in.status
     *
     * @param status the value for productpage_in.status
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductPage getPage() {
		return page;
	}

	public void setPage(ProductPage page) {
		this.page = page;
	}

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}
    
}