package com.grotek.pojo;

import java.util.Date;

public class ProductBox_out {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_out.id
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_out.pid
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    private ProductBox box;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_out.date
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_out.count
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_out.did
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_out.status
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    private Integer status;
    
    private Integer aid;
    
    private Integer psid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_out.id
     *
     * @return the value of productbox_out.id
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_out.id
     *
     * @param id the value for productbox_out.id
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_out.date
     *
     * @return the value of productbox_out.date
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_out.date
     *
     * @param date the value for productbox_out.date
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_out.count
     *
     * @return the value of productbox_out.count
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_out.count
     *
     * @param count the value for productbox_out.count
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_out.status
     *
     * @return the value of productbox_out.status
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_out.status
     *
     * @param status the value for productbox_out.status
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductBox getBox() {
		return box;
	}

	public void setBox(ProductBox box) {
		this.box = box;
	}

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	public Integer getAid() {
		return aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public Integer getPsid() {
		return psid;
	}

	public void setPsid(Integer psid) {
		this.psid = psid;
	}
    
}