package com.grotek.pojo;

public class ProductPack_Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpack_store.id
     *
     * @mbggenerated Thu Jun 30 13:37:36 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpack_store.pid
     *
     * @mbggenerated Thu Jun 30 13:37:36 CST 2016
     */
    private ProductPack pack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpack_store.count
     *
     * @mbggenerated Thu Jun 30 13:37:36 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpack_store.status
     *
     * @mbggenerated Thu Jun 30 13:37:36 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpack_store.id
     *
     * @return the value of productpack_store.id
     *
     * @mbggenerated Thu Jun 30 13:37:36 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpack_store.id
     *
     * @param id the value for productpack_store.id
     *
     * @mbggenerated Thu Jun 30 13:37:36 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpack_store.count
     *
     * @return the value of productpack_store.count
     *
     * @mbggenerated Thu Jun 30 13:37:36 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpack_store.count
     *
     * @param count the value for productpack_store.count
     *
     * @mbggenerated Thu Jun 30 13:37:36 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpack_store.status
     *
     * @return the value of productpack_store.status
     *
     * @mbggenerated Thu Jun 30 13:37:36 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpack_store.status
     *
     * @param status the value for productpack_store.status
     *
     * @mbggenerated Thu Jun 30 13:37:36 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductPack getPack() {
		return pack;
	}

	public void setPack(ProductPack pack) {
		this.pack = pack;
	}
    
}