package com.grotek.pojo;

import java.util.Date;

public class ProductRaw_Price {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productraw_price.id
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productraw_price.pid
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    private ProductRaw productRaw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productraw_price.price
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productraw_price.date
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productraw_price.status
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productraw_price.id
     *
     * @return the value of productraw_price.id
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productraw_price.id
     *
     * @param id the value for productraw_price.id
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productraw_price.price
     *
     * @return the value of productraw_price.price
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productraw_price.price
     *
     * @param price the value for productraw_price.price
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productraw_price.date
     *
     * @return the value of productraw_price.date
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productraw_price.date
     *
     * @param date the value for productraw_price.date
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productraw_price.status
     *
     * @return the value of productraw_price.status
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productraw_price.status
     *
     * @param status the value for productraw_price.status
     *
     * @mbggenerated Tue Jun 21 09:35:11 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductRaw getProductRaw() {
		return productRaw;
	}

	public void setProductRaw(ProductRaw productRaw) {
		this.productRaw = productRaw;
	}
    
}