package com.grotek.pojo;

public class ProductRaw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productrawinfo.id
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productrawinfo.code
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productrawinfo.name
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productrawinfo.description
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productrawinfo.status
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    private Integer status;
    
    private GrotekUnit unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productrawinfo.id
     *
     * @return the value of productrawinfo.id
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productrawinfo.id
     *
     * @param id the value for productrawinfo.id
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productrawinfo.code
     *
     * @return the value of productrawinfo.code
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productrawinfo.code
     *
     * @param code the value for productrawinfo.code
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productrawinfo.name
     *
     * @return the value of productrawinfo.name
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productrawinfo.name
     *
     * @param name the value for productrawinfo.name
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productrawinfo.description
     *
     * @return the value of productrawinfo.description
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productrawinfo.description
     *
     * @param description the value for productrawinfo.description
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productrawinfo.status
     *
     * @return the value of productrawinfo.status
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productrawinfo.status
     *
     * @param status the value for productrawinfo.status
     *
     * @mbggenerated Mon Jun 20 11:08:50 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public GrotekUnit getUnit() {
		return unit;
	}

	public void setUnit(GrotekUnit unit) {
		this.unit = unit;
	}
    
}