package com.grotek.pojo;

public class ProductBox {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productboxinfo.id
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productboxinfo.code
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productboxinfo.name
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productboxinfo.specification
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    private String specification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productboxinfo.unit
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productboxinfo.netcontent
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    private Double netcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productboxinfo.piececount
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    private Integer piececount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productboxinfo.piececontent
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    private Double piececontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productboxinfo.status
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    private Integer status;
    
    private GrotekUnit gu;
    
    private Double kg;
    
    private ManureType type;
    
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productboxinfo.id
     *
     * @return the value of productboxinfo.id
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productboxinfo.id
     *
     * @param id the value for productboxinfo.id
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productboxinfo.code
     *
     * @return the value of productboxinfo.code
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productboxinfo.code
     *
     * @param code the value for productboxinfo.code
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productboxinfo.name
     *
     * @return the value of productboxinfo.name
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productboxinfo.name
     *
     * @param name the value for productboxinfo.name
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productboxinfo.specification
     *
     * @return the value of productboxinfo.specification
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public String getSpecification() {
        return specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productboxinfo.specification
     *
     * @param specification the value for productboxinfo.specification
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public void setSpecification(String specification) {
        this.specification = specification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productboxinfo.unit
     *
     * @return the value of productboxinfo.unit
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productboxinfo.unit
     *
     * @param unit the value for productboxinfo.unit
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productboxinfo.netcontent
     *
     * @return the value of productboxinfo.netcontent
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public Double getNetcontent() {
        return netcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productboxinfo.netcontent
     *
     * @param netcontent the value for productboxinfo.netcontent
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public void setNetcontent(Double netcontent) {
        this.netcontent = netcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productboxinfo.piececount
     *
     * @return the value of productboxinfo.piececount
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public Integer getPiececount() {
        return piececount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productboxinfo.piececount
     *
     * @param piececount the value for productboxinfo.piececount
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public void setPiececount(Integer piececount) {
        this.piececount = piececount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productboxinfo.piececontent
     *
     * @return the value of productboxinfo.piececontent
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public Double getPiececontent() {
        return piececontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productboxinfo.piececontent
     *
     * @param piececontent the value for productboxinfo.piececontent
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public void setPiececontent(Double piececontent) {
        this.piececontent = piececontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productboxinfo.status
     *
     * @return the value of productboxinfo.status
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productboxinfo.status
     *
     * @param status the value for productboxinfo.status
     *
     * @mbggenerated Mon Jul 04 10:49:05 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public GrotekUnit getGu() {
		return gu;
	}

	public void setGu(GrotekUnit gu) {
		this.gu = gu;
	}

	public Double getKg() {
		return kg;
	}

	public void setKg(Double kg) {
		this.kg = kg;
	}

	public ManureType getType() {
		return type;
	}

	public void setType(ManureType type) {
		this.type = type;
	}

	public String getPinyin() {
		return pinyin;
	}

	public void setPinyin(String pinyin) {
		this.pinyin = pinyin;
	}
    
}