package com.grotek.pojo;

public class ProductBox_Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_store.id
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_store.pid
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    private ProductBox box;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_store.count
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_store.status
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_store.id
     *
     * @return the value of productbox_store.id
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_store.id
     *
     * @param id the value for productbox_store.id
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_store.count
     *
     * @return the value of productbox_store.count
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_store.count
     *
     * @param count the value for productbox_store.count
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_store.status
     *
     * @return the value of productbox_store.status
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_store.status
     *
     * @param status the value for productbox_store.status
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductBox getBox() {
		return box;
	}

	public void setBox(ProductBox box) {
		this.box = box;
	}
    
}