package com.grotek.pojo;

import java.util.Date;

public class ProductBox_Price {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_price.id
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_price.pid
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    private ProductBox box;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_price.unitprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    private Double unitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_price.pieceprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    private Double pieceprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_price.dealer_unitprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    private Double dealerUnitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_price.dealer_pieceprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    private Double dealerPieceprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_price.retail_unitprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    private Double retailUnitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_price.update_date
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productbox_price.status
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_price.id
     *
     * @return the value of productbox_price.id
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_price.id
     *
     * @param id the value for productbox_price.id
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_price.unitprice
     *
     * @return the value of productbox_price.unitprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public Double getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_price.unitprice
     *
     * @param unitprice the value for productbox_price.unitprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_price.pieceprice
     *
     * @return the value of productbox_price.pieceprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public Double getPieceprice() {
        return pieceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_price.pieceprice
     *
     * @param pieceprice the value for productbox_price.pieceprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public void setPieceprice(Double pieceprice) {
        this.pieceprice = pieceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_price.dealer_unitprice
     *
     * @return the value of productbox_price.dealer_unitprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public Double getDealerUnitprice() {
        return dealerUnitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_price.dealer_unitprice
     *
     * @param dealerUnitprice the value for productbox_price.dealer_unitprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public void setDealerUnitprice(Double dealerUnitprice) {
        this.dealerUnitprice = dealerUnitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_price.dealer_pieceprice
     *
     * @return the value of productbox_price.dealer_pieceprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public Double getDealerPieceprice() {
        return dealerPieceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_price.dealer_pieceprice
     *
     * @param dealerPieceprice the value for productbox_price.dealer_pieceprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public void setDealerPieceprice(Double dealerPieceprice) {
        this.dealerPieceprice = dealerPieceprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_price.retail_unitprice
     *
     * @return the value of productbox_price.retail_unitprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public Double getRetailUnitprice() {
        return retailUnitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_price.retail_unitprice
     *
     * @param retailUnitprice the value for productbox_price.retail_unitprice
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public void setRetailUnitprice(Double retailUnitprice) {
        this.retailUnitprice = retailUnitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_price.update_date
     *
     * @return the value of productbox_price.update_date
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_price.update_date
     *
     * @param updateDate the value for productbox_price.update_date
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productbox_price.status
     *
     * @return the value of productbox_price.status
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productbox_price.status
     *
     * @param status the value for productbox_price.status
     *
     * @mbggenerated Mon Jul 04 14:53:39 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductBox getBox() {
		return box;
	}

	public void setBox(ProductBox box) {
		this.box = box;
	}
    
}