package com.grotek.pojo;

import java.util.Date;

public class ProductPack_In {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpack_in.id
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpack_in.pid
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    private ProductPack pack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpack_in.date
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpack_in.count
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpack_in.did
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpack_in.status
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpack_in.id
     *
     * @return the value of productpack_in.id
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpack_in.id
     *
     * @param id the value for productpack_in.id
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpack_in.date
     *
     * @return the value of productpack_in.date
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpack_in.date
     *
     * @param date the value for productpack_in.date
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpack_in.count
     *
     * @return the value of productpack_in.count
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpack_in.count
     *
     * @param count the value for productpack_in.count
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpack_in.status
     *
     * @return the value of productpack_in.status
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpack_in.status
     *
     * @param status the value for productpack_in.status
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductPack getPack() {
		return pack;
	}

	public void setPack(ProductPack pack) {
		this.pack = pack;
	}

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}
    
}