package com.grotek.pojo;

import java.util.Date;

public class ProductLabor_Time {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_time.id
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_time.plid
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    private ProductLabor labor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_time.workhours
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    private Double workhours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_time.overhours
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    private Double overhours;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_time.pay
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    private Double pay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_time.date
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productlabor_time.status
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    private Integer status;
    
    private Double bonus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlabor_time.id
     *
     * @return the value of productlabor_time.id
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlabor_time.id
     *
     * @param id the value for productlabor_time.id
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlabor_time.workhours
     *
     * @return the value of productlabor_time.workhours
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public Double getWorkhours() {
        return workhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlabor_time.workhours
     *
     * @param workhours the value for productlabor_time.workhours
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public void setWorkhours(Double workhours) {
        this.workhours = workhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlabor_time.overhours
     *
     * @return the value of productlabor_time.overhours
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public Double getOverhours() {
        return overhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlabor_time.overhours
     *
     * @param overhours the value for productlabor_time.overhours
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public void setOverhours(Double overhours) {
        this.overhours = overhours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlabor_time.pay
     *
     * @return the value of productlabor_time.pay
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public Double getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlabor_time.pay
     *
     * @param pay the value for productlabor_time.pay
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public void setPay(Double pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlabor_time.date
     *
     * @return the value of productlabor_time.date
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlabor_time.date
     *
     * @param date the value for productlabor_time.date
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productlabor_time.status
     *
     * @return the value of productlabor_time.status
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productlabor_time.status
     *
     * @param status the value for productlabor_time.status
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductLabor getLabor() {
		return labor;
	}

	public void setLabor(ProductLabor labor) {
		this.labor = labor;
	}

	public Double getBonus() {
		return bonus;
	}

	public void setBonus(Double bonus) {
		this.bonus = bonus;
	}
    
    
}