package com.grotek.pojo;

import java.util.Date;

public class ProductPack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpackinfo.id
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpackinfo.code
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpackinfo.name
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpackinfo.type
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    private PackType type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpackinfo.price
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpackinfo.uadate_date
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    private Date uadateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productpackinfo.status
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpackinfo.id
     *
     * @return the value of productpackinfo.id
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpackinfo.id
     *
     * @param id the value for productpackinfo.id
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpackinfo.code
     *
     * @return the value of productpackinfo.code
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpackinfo.code
     *
     * @param code the value for productpackinfo.code
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpackinfo.name
     *
     * @return the value of productpackinfo.name
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpackinfo.name
     *
     * @param name the value for productpackinfo.name
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpackinfo.price
     *
     * @return the value of productpackinfo.price
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpackinfo.price
     *
     * @param price the value for productpackinfo.price
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpackinfo.uadate_date
     *
     * @return the value of productpackinfo.uadate_date
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public Date getUadateDate() {
        return uadateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpackinfo.uadate_date
     *
     * @param uadateDate the value for productpackinfo.uadate_date
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public void setUadateDate(Date uadateDate) {
        this.uadateDate = uadateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productpackinfo.status
     *
     * @return the value of productpackinfo.status
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productpackinfo.status
     *
     * @param status the value for productpackinfo.status
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public PackType getType() {
		return type;
	}

	public void setType(PackType type) {
		this.type = type;
	}
    
}