package com.grotek.pojo;

import java.util.Date;

public class ProjectWork {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.id
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.eid
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private Employee employee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.did
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.jid
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private JobtypeDic type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.content
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.place
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.setime
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private String setime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.laborhour
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private Double laborhour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.date
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.sid
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private Employee leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.check
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private Integer checked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projectwork.status
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectwork.id
     *
     * @return the value of projectwork.id
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectwork.id
     *
     * @param id the value for projectwork.id
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectwork.content
     *
     * @return the value of projectwork.content
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectwork.content
     *
     * @param content the value for projectwork.content
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectwork.place
     *
     * @return the value of projectwork.place
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectwork.place
     *
     * @param place the value for projectwork.place
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public void setPlace(String place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectwork.setime
     *
     * @return the value of projectwork.setime
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public String getSetime() {
        return setime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectwork.setime
     *
     * @param setime the value for projectwork.setime
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public void setSetime(String setime) {
        this.setime = setime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectwork.laborhour
     *
     * @return the value of projectwork.laborhour
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public Double getLaborhour() {
        return laborhour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectwork.laborhour
     *
     * @param laborhour the value for projectwork.laborhour
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public void setLaborhour(Double laborhour) {
        this.laborhour = laborhour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectwork.date
     *
     * @return the value of projectwork.date
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectwork.date
     *
     * @param date the value for projectwork.date
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projectwork.status
     *
     * @return the value of projectwork.status
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projectwork.status
     *
     * @param status the value for projectwork.status
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	public JobtypeDic getType() {
		return type;
	}

	public void setType(JobtypeDic type) {
		this.type = type;
	}

	public Employee getLeader() {
		return leader;
	}

	public void setLeader(Employee leader) {
		this.leader = leader;
	}

	public Integer getChecked() {
		return checked;
	}

	public void setChecked(Integer checked) {
		this.checked = checked;
	}
    
    
}