package com.grotek.pojo;

import java.util.Date;

public class ReferencePackWeight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference_packweight.id
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference_packweight.pid
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    private ProductPack pack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference_packweight.material
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    private String material;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference_packweight.uweight1
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    private Double uweight1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference_packweight.uprice
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    private Double uprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference_packweight.uweight2
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    private Double uweight2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference_packweight.ccount
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    private Double ccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reference_packweight.status
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    private Integer status;
    
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference_packweight.id
     *
     * @return the value of reference_packweight.id
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference_packweight.id
     *
     * @param id the value for reference_packweight.id
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference_packweight.material
     *
     * @return the value of reference_packweight.material
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public String getMaterial() {
        return material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference_packweight.material
     *
     * @param material the value for reference_packweight.material
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public void setMaterial(String material) {
        this.material = material;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference_packweight.uweight1
     *
     * @return the value of reference_packweight.uweight1
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public Double getUweight1() {
        return uweight1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference_packweight.uweight1
     *
     * @param uweight1 the value for reference_packweight.uweight1
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public void setUweight1(Double uweight1) {
        this.uweight1 = uweight1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference_packweight.uprice
     *
     * @return the value of reference_packweight.uprice
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public Double getUprice() {
        return uprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference_packweight.uprice
     *
     * @param uprice the value for reference_packweight.uprice
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public void setUprice(Double uprice) {
        this.uprice = uprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference_packweight.uweight2
     *
     * @return the value of reference_packweight.uweight2
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public Double getUweight2() {
        return uweight2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference_packweight.uweight2
     *
     * @param uweight2 the value for reference_packweight.uweight2
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public void setUweight2(Double uweight2) {
        this.uweight2 = uweight2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference_packweight.ccount
     *
     * @return the value of reference_packweight.ccount
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public Double getCcount() {
        return ccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference_packweight.ccount
     *
     * @param ccount the value for reference_packweight.ccount
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public void setCcount(Double ccount) {
        this.ccount = ccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reference_packweight.status
     *
     * @return the value of reference_packweight.status
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reference_packweight.status
     *
     * @param status the value for reference_packweight.status
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public ProductPack getPack() {
		return pack;
	}

	public void setPack(ProductPack pack) {
		this.pack = pack;
	}

	public Date getUpdatedate() {
		return updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}
    
}