package com.grotek.pojo;

public class RewardDic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_dic.id
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_dic.item
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private String item;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_dic.amount
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_dic.description
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_dic.status
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_dic.id
     *
     * @return the value of reward_dic.id
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_dic.id
     *
     * @param id the value for reward_dic.id
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_dic.item
     *
     * @return the value of reward_dic.item
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_dic.item
     *
     * @param item the value for reward_dic.item
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setItem(String item) {
        this.item = item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_dic.amount
     *
     * @return the value of reward_dic.amount
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_dic.amount
     *
     * @param amount the value for reward_dic.amount
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_dic.description
     *
     * @return the value of reward_dic.description
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_dic.description
     *
     * @param description the value for reward_dic.description
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_dic.status
     *
     * @return the value of reward_dic.status
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_dic.status
     *
     * @param status the value for reward_dic.status
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}