package com.grotek.pojo;

public class ShopTypeDic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoptype_dic.id
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoptype_dic.name
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoptype_dic.status
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoptype_dic.id
     *
     * @return the value of shoptype_dic.id
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoptype_dic.id
     *
     * @param id the value for shoptype_dic.id
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoptype_dic.name
     *
     * @return the value of shoptype_dic.name
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoptype_dic.name
     *
     * @param name the value for shoptype_dic.name
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoptype_dic.status
     *
     * @return the value of shoptype_dic.status
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoptype_dic.status
     *
     * @param status the value for shoptype_dic.status
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}