package com.grotek.pojo;

import java.util.Date;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.springframework.format.annotation.DateTimeFormat;

@JsonIgnoreProperties(ignoreUnknown=true)
public class TravelRbsmItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_rbsm_item.id
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_rbsm_item.pid
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_rbsm_item.tid
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    private TravelExsType type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_rbsm_item.eid
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    private String eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_rbsm_item.amount
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column travel_rbsm_item.status
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    private Integer status;
    
    private Integer gasolineid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_rbsm_item.id
     *
     * @return the value of travel_rbsm_item.id
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_rbsm_item.id
     *
     * @param id the value for travel_rbsm_item.id
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_rbsm_item.pid
     *
     * @return the value of travel_rbsm_item.pid
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_rbsm_item.pid
     *
     * @param pid the value for travel_rbsm_item.pid
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_rbsm_item.eid
     *
     * @return the value of travel_rbsm_item.eid
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_rbsm_item.eid
     *
     * @param eid the value for travel_rbsm_item.eid
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    public void setEid(String eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_rbsm_item.amount
     *
     * @return the value of travel_rbsm_item.amount
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_rbsm_item.amount
     *
     * @param amount the value for travel_rbsm_item.amount
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column travel_rbsm_item.status
     *
     * @return the value of travel_rbsm_item.status
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column travel_rbsm_item.status
     *
     * @param status the value for travel_rbsm_item.status
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public TravelExsType getType() {
		return type;
	}

	public void setType(TravelExsType type) {
		this.type = type;
	}

	public Integer getGasolineid() {
		return gasolineid;
	}

	public void setGasolineid(Integer gasolineid) {
		this.gasolineid = gasolineid;
	}
    
    
}