package com.grotek.pojo;

import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

public class Weekly {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.id
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.eid
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    private Employee employee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.stime
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date stime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.etime
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date etime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.estatus
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    private Integer estatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.checked
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    private Integer checked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.sid
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly.status
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.id
     *
     * @return the value of weekly.id
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    
    private List<WeeklyItem> items;
    
    private Integer count;
    
    private String remark;
    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.id
     *
     * @param id the value for weekly.id
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.stime
     *
     * @return the value of weekly.stime
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public Date getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.stime
     *
     * @param stime the value for weekly.stime
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public void setStime(Date stime) {
        this.stime = stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.etime
     *
     * @return the value of weekly.etime
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public Date getEtime() {
        return etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.etime
     *
     * @param etime the value for weekly.etime
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public void setEtime(Date etime) {
        this.etime = etime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.estatus
     *
     * @return the value of weekly.estatus
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public Integer getEstatus() {
        return estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.estatus
     *
     * @param estatus the value for weekly.estatus
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.checked
     *
     * @return the value of weekly.checked
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public Integer getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.checked
     *
     * @param checked the value for weekly.checked
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public void setChecked(Integer checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.sid
     *
     * @return the value of weekly.sid
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.sid
     *
     * @param sid the value for weekly.sid
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly.status
     *
     * @return the value of weekly.status
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly.status
     *
     * @param status the value for weekly.status
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Employee getEmployee() {
		return employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public List<WeeklyItem> getItems() {
		return items;
	}

	public void setItems(List<WeeklyItem> items) {
		this.items = items;
	}

	public Integer getCount() {
		if(items!=null && items.size()>0){
			return items.size();
		}
		else{
			return count;
		}
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
    
}