package com.grotek.pojo;

public class WeeklyItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.id
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.wid
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private Integer wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.did
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private Dealer dealer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.tid
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private JobtypeDic type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.content
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.mon
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private Double mon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.tue
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private Double tue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.wed
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private Double wed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.thu
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private Double thu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.fri
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private Double fri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.sat
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private Double sat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.sun
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private Double sun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekly_item.status
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    private Integer status;
    
    private Double total;
    
    private String place;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly_item.id
     *
     * @return the value of weekly_item.id
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly_item.id
     *
     * @param id the value for weekly_item.id
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly_item.wid
     *
     * @return the value of weekly_item.wid
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public Integer getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly_item.wid
     *
     * @param wid the value for weekly_item.wid
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public void setWid(Integer wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly_item.content
     *
     * @return the value of weekly_item.content
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly_item.content
     *
     * @param content the value for weekly_item.content
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly_item.mon
     *
     * @return the value of weekly_item.mon
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public Double getMon() {
        return mon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly_item.mon
     *
     * @param mon the value for weekly_item.mon
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public void setMon(Double mon) {
        this.mon = mon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly_item.tue
     *
     * @return the value of weekly_item.tue
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public Double getTue() {
        return tue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly_item.tue
     *
     * @param tue the value for weekly_item.tue
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public void setTue(Double tue) {
        this.tue = tue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly_item.wed
     *
     * @return the value of weekly_item.wed
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public Double getWed() {
        return wed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly_item.wed
     *
     * @param wed the value for weekly_item.wed
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public void setWed(Double wed) {
        this.wed = wed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly_item.thu
     *
     * @return the value of weekly_item.thu
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public Double getThu() {
        return thu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly_item.thu
     *
     * @param thu the value for weekly_item.thu
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public void setThu(Double thu) {
        this.thu = thu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly_item.fri
     *
     * @return the value of weekly_item.fri
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public Double getFri() {
        return fri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly_item.fri
     *
     * @param fri the value for weekly_item.fri
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public void setFri(Double fri) {
        this.fri = fri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly_item.sat
     *
     * @return the value of weekly_item.sat
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public Double getSat() {
        return sat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly_item.sat
     *
     * @param sat the value for weekly_item.sat
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public void setSat(Double sat) {
        this.sat = sat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly_item.sun
     *
     * @return the value of weekly_item.sun
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public Double getSun() {
        return sun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly_item.sun
     *
     * @param sun the value for weekly_item.sun
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public void setSun(Double sun) {
        this.sun = sun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekly_item.status
     *
     * @return the value of weekly_item.status
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekly_item.status
     *
     * @param status the value for weekly_item.status
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public Dealer getDealer() {
		return dealer;
	}

	public void setDealer(Dealer dealer) {
		this.dealer = dealer;
	}

	public JobtypeDic getType() {
		return type;
	}

	public void setType(JobtypeDic type) {
		this.type = type;
	}

	public Double getTotal() {
		return total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public String getPlace() {
		return place;
	}

	public void setPlace(String place) {
		this.place = place;
	}
    
    
}