package com.grotek.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;
import com.grotek.pojo.DealerValue;

public interface DealerValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_value
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_value
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    int insert(DealerValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_value
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    int insertSelective(DealerValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_value
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    DealerValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_value
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    int updateByPrimaryKeySelective(DealerValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealer_value
     *
     * @mbggenerated Wed Jul 13 17:27:29 CST 2016
     */
    int updateByPrimaryKey(DealerValue record);
    
    List<DealerValue> findDealerValues(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<DealerValue> getDealerValues(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    List<DealerValue> getByDid(@Param("did")int did,@Param("pageable")PageRequest pageable);
    
    int allCountByDid(int did);
    
    List<DealerValue> getByDateAndDid(@Param("did")int did,@Param("stime")Date stime,@Param("etime")Date etime);
    
    List<DealerValue> getByDateAndEid(@Param("eid")String eid,@Param("stime")Date stime,@Param("etime")Date etime);
}