package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.Dealer;
import com.grotek.pojo.Employee;

public interface DealerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealerinfo
     *
     * @mbggenerated Tue Jun 21 14:41:16 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealerinfo
     *
     * @mbggenerated Tue Jun 21 14:41:16 CST 2016
     */
    int insert(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealerinfo
     *
     * @mbggenerated Tue Jun 21 14:41:16 CST 2016
     */
    int insertSelective(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealerinfo
     *
     * @mbggenerated Tue Jun 21 14:41:16 CST 2016
     */
    Dealer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealerinfo
     *
     * @mbggenerated Tue Jun 21 14:41:16 CST 2016
     */
    int updateByPrimaryKeySelective(Dealer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dealerinfo
     *
     * @mbggenerated Tue Jun 21 14:41:16 CST 2016
     */
    int updateByPrimaryKey(Dealer record);
    
    List<Dealer> findDealer(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<Dealer> getDealers(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    List<Dealer> findDealerByEid(@Param("eid")String eid,@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<Dealer> getDealersByEid(@Param("eid")String eid,@Param("pageable")PageRequest pageable);
    
    int searchCountByEid(@Param("eid")String eid,@Param("key")String key);
    
    int allCountByEid(String eid);
    
    List<Dealer> allDealers();
    
    List<Dealer> hzDealers();
}