package com.grotek.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.grotek.pojo.DeliveryOrder;

public interface DeliveryOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    int insert(DeliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    int insertSelective(DeliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    DeliveryOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    int updateByPrimaryKeySelective(DeliveryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delivery_order
     *
     * @mbggenerated Mon Jul 25 15:33:26 CST 2016
     */
    int updateByPrimaryKey(DeliveryOrder record);
    
    DeliveryOrder getByAid(int aid);
    
    List<DeliveryOrder> getByDealerAndTime(@Param("did")int did,@Param("stime")Date stime,@Param("etime")Date etime);
    
}