package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.grotek.pojo.DepartmentDic;

public interface DepartmentDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int insert(DepartmentDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int insertSelective(DepartmentDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    DepartmentDic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int updateByPrimaryKeySelective(DepartmentDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int updateByPrimaryKey(DepartmentDic record);
    
    List<DepartmentDic> getAllDepartmentDics();
    
    int checkNameAndCode(@Param("name")String name,@Param("code")String code);
}