package com.grotek.dao;

import java.util.List;

import com.grotek.pojo.District;

public interface DistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Tue Jun 21 15:14:57 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Tue Jun 21 15:14:57 CST 2016
     */
    int insert(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Tue Jun 21 15:14:57 CST 2016
     */
    int insertSelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Tue Jun 21 15:14:57 CST 2016
     */
    District selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Tue Jun 21 15:14:57 CST 2016
     */
    int updateByPrimaryKeySelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table district
     *
     * @mbggenerated Tue Jun 21 15:14:57 CST 2016
     */
    int updateByPrimaryKey(District record);
    
    List<District> getAll();
}