package com.grotek.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.EmployeeFee;
import com.grotek.pojo.ExsRbsm;

public interface EmployeeFeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_fee
     *
     * @mbggenerated Sat Jul 23 10:12:11 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_fee
     *
     * @mbggenerated Sat Jul 23 10:12:11 CST 2016
     */
    int insert(EmployeeFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_fee
     *
     * @mbggenerated Sat Jul 23 10:12:11 CST 2016
     */
    int insertSelective(EmployeeFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_fee
     *
     * @mbggenerated Sat Jul 23 10:12:11 CST 2016
     */
    EmployeeFee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_fee
     *
     * @mbggenerated Sat Jul 23 10:12:11 CST 2016
     */
    int updateByPrimaryKeySelective(EmployeeFee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_fee
     *
     * @mbggenerated Sat Jul 23 10:12:11 CST 2016
     */
    int updateByPrimaryKey(EmployeeFee record);
    
    List<EmployeeFee> getByEid(@Param("eid")String eid,@Param("pageable")PageRequest pageable);
    
    int allCountByEid(String eid);
    
    List<EmployeeFee> findByEid(@Param("eid")String eid,@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    int searchCountByEid(@Param("eid")String eid,@Param("key")String key);
    
    List<EmployeeFee> getByDid(@Param("did")int did,@Param("pageable")PageRequest pageable);
    
    int allCountByDid(int did);
    
    List<EmployeeFee> getByED(@Param("eid")String eid,@Param("did")int did,@Param("pageable")PageRequest pageable);
    
    int allCountByED(@Param("eid")String eid,@Param("did")int did);
    
    List<EmployeeFee> getByDateAndDid(@Param("did")int did,@Param("stime")Date stime,@Param("etime")Date etime);
}