package com.grotek.dao;

import com.grotek.pojo.EmployeeGasoline;

public interface EmployeeGasolineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_gasoline
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_gasoline
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    int insert(EmployeeGasoline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_gasoline
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    int insertSelective(EmployeeGasoline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_gasoline
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    EmployeeGasoline selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_gasoline
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    int updateByPrimaryKeySelective(EmployeeGasoline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_gasoline
     *
     * @mbggenerated Sun Aug 21 09:32:32 CST 2016
     */
    int updateByPrimaryKey(EmployeeGasoline record);
    
    EmployeeGasoline getByEid(String eid);
}