package com.grotek.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.EmployeeReward;

public interface EmployeeRewardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_reward
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_reward
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    int insert(EmployeeReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_reward
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    int insertSelective(EmployeeReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_reward
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    EmployeeReward selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_reward
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    int updateByPrimaryKeySelective(EmployeeReward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_reward
     *
     * @mbggenerated Thu Jun 16 14:23:52 CST 2016
     */
    int updateByPrimaryKey(EmployeeReward record);
    
    List<EmployeeReward> getEmployeeRewardsByEid(String emid);
    
    List<EmployeeReward> getRewards(PageRequest pageable);
    
    List<EmployeeReward> getByEidAndDate(@Param("eid")String eid,@Param("stime")Date stime,@Param("etime")Date etime);
    
    int allCount();
}