package com.grotek.dao;

import java.awt.print.Pageable;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.Employee;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    Employee selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 10 14:06:55 CST 2016
     */
    int updateByPrimaryKey(Employee record);
    
    List<Employee> findEmployee(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<Employee> getEmployees(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    int checkCode(String code);
    
    Employee getByMobile(String mobile);
    
    List<Employee> findMembers(@Param("key")String key,@Param("sid")String sid,@Param("pageable")PageRequest pageable);
    
    List<Employee> getMembers(@Param("sid")String sid,@Param("pageable")PageRequest pageable);
    
    int searchCountMembers(@Param("key")String key,@Param("sid")String sid);
    
    int allCountMembers(@Param("sid")String sid);
    
}