package com.grotek.dao;

import java.util.List;

import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.EmployeeProm;
import com.grotek.pojo.EmployeeReward;

public interface EmployeePromMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_promote
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_promote
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    int insert(EmployeeProm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_promote
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    int insertSelective(EmployeeProm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_promote
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    EmployeeProm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_promote
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    int updateByPrimaryKeySelective(EmployeeProm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_promote
     *
     * @mbggenerated Wed Jun 15 10:53:10 CST 2016
     */
    int updateByPrimaryKey(EmployeeProm record);
    
    List<EmployeeProm> getEmployeePromsByEid(String emid);
    
    List<EmployeeProm> getPromotes(PageRequest pageable);
    
    int allCount();
}