package com.grotek.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ExsRbsm;

public interface ExsRbsmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_rbsm
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_rbsm
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    int insert(ExsRbsm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_rbsm
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    int insertSelective(ExsRbsm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_rbsm
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    ExsRbsm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_rbsm
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    int updateByPrimaryKeySelective(ExsRbsm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_rbsm
     *
     * @mbggenerated Wed Jul 20 16:09:20 CST 2016
     */
    int updateByPrimaryKey(ExsRbsm record);
    
    List<ExsRbsm> getExsRbsmsByEid(@Param("eid")String eid,@Param("pageable")PageRequest pageable);
    
    int allCountByEid(String eid);
    
    List<ExsRbsm> findExsRbsms(@Param("eid")String eid,@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    int searchCountByEid(@Param("eid")String eid,@Param("key")String key);
    
    List<ExsRbsm> findByFullname(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    int searchCountByFullname(@Param("key")String key);
    
    List<ExsRbsm> getExsRbsms(@Param("pageable")PageRequest pageable);
    
    List<ExsRbsm> getByEidAndDate(@Param("eid")String eid,@Param("stime")Date stime,@Param("etime")Date etime);
    
    List<ExsRbsm> getByDidAndDate(@Param("did")int did,@Param("stime")Date stime,@Param("etime")Date etime);
    
    int allCount();
    
    List<ExsRbsm> findCheckpending(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    int searchCountCheckpending(@Param("key")String key);
    
    List<ExsRbsm> getCheckpending(@Param("pageable")PageRequest pageable);
    
    int allCheckpendingCount();
    
    List<ExsRbsm> findChecked(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    int searchCountChecked(@Param("key")String key);
    
    List<ExsRbsm> getChecked(@Param("pageable")PageRequest pageable);
    
    int allCheckedCount();
    
    List<ExsRbsm> findACheckpending(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    int searchCountACheckpending(@Param("key")String key);
    
    List<ExsRbsm> getACheckpending(@Param("pageable")PageRequest pageable);
    
    int allACheckpendingCount();
    
    List<ExsRbsm> findAChecked(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    int searchCountAChecked(@Param("key")String key);
    
    List<ExsRbsm> getAChecked(@Param("pageable")PageRequest pageable);
    
    int allACheckedCount();
    
    List<ExsRbsm> findFinal(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    int searchCountFinal(@Param("key")String key);
    
    List<ExsRbsm> getFinal(@Param("pageable")PageRequest pageable);
    
    int allFinalCount();
}