package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.grotek.pojo.ExsType;

public interface ExsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_type
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_type
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    int insert(ExsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_type
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    int insertSelective(ExsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_type
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    ExsType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_type
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    int updateByPrimaryKeySelective(ExsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exs_type
     *
     * @mbggenerated Mon Aug 22 09:01:29 CST 2016
     */
    int updateByPrimaryKey(ExsType record);
    
    List<ExsType> getAll();
    
    int checkName(@Param("name")String name);
}