package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.grotek.pojo.GrotekUnit;

public interface GrotekUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    int insert(GrotekUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    int insertSelective(GrotekUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    GrotekUnit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    int updateByPrimaryKeySelective(GrotekUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Wed Sep 21 10:41:11 CST 2016
     */
    int updateByPrimaryKey(GrotekUnit record);
    
    List<GrotekUnit> getAll();
    
    int checkName(@Param("name")String name);
}