package com.grotek.dao;

import java.util.List;

import com.grotek.pojo.InSchemePages;

public interface InSchemePagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_pages
     *
     * @mbggenerated Tue Jul 05 10:01:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_pages
     *
     * @mbggenerated Tue Jul 05 10:01:49 CST 2016
     */
    int insert(InSchemePages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_pages
     *
     * @mbggenerated Tue Jul 05 10:01:49 CST 2016
     */
    int insertSelective(InSchemePages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_pages
     *
     * @mbggenerated Tue Jul 05 10:01:49 CST 2016
     */
    InSchemePages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_pages
     *
     * @mbggenerated Tue Jul 05 10:01:49 CST 2016
     */
    int updateByPrimaryKeySelective(InSchemePages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_pages
     *
     * @mbggenerated Tue Jul 05 10:01:49 CST 2016
     */
    int updateByPrimaryKey(InSchemePages record);
    
    List<InSchemePages> getBySid(int sid);
}