package com.grotek.dao;

import java.util.List;

import com.grotek.pojo.InSchemeRaws;

public interface InSchemeRawsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_raws
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_raws
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    int insert(InSchemeRaws record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_raws
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    int insertSelective(InSchemeRaws record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_raws
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    InSchemeRaws selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_raws
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    int updateByPrimaryKeySelective(InSchemeRaws record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_scheme_raws
     *
     * @mbggenerated Tue Jul 05 09:16:55 CST 2016
     */
    int updateByPrimaryKey(InSchemeRaws record);
    
    List<InSchemeRaws> getBySid(int sid);
}