package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.grotek.pojo.ManureType;

public interface ManureTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manure_type
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manure_type
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    int insert(ManureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manure_type
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    int insertSelective(ManureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manure_type
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    ManureType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manure_type
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    int updateByPrimaryKeySelective(ManureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manure_type
     *
     * @mbggenerated Thu Sep 29 10:16:58 CST 2016
     */
    int updateByPrimaryKey(ManureType record);
    
    List<ManureType> getAll();
    
    int checkName(@Param("name")String name);
}