package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.grotek.pojo.PositionDic;

public interface PositionDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int insert(PositionDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int insertSelective(PositionDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    PositionDic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int updateByPrimaryKeySelective(PositionDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int updateByPrimaryKey(PositionDic record);
    
    List<PositionDic> getAllPositionDics();
    
    int checkName(@Param("name")String name);
}