package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductLabor_Cost;

public interface ProductLabor_CostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_cost
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_cost
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    int insert(ProductLabor_Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_cost
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    int insertSelective(ProductLabor_Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_cost
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    ProductLabor_Cost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_cost
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    int updateByPrimaryKeySelective(ProductLabor_Cost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_cost
     *
     * @mbggenerated Fri Jul 08 14:49:47 CST 2016
     */
    int updateByPrimaryKey(ProductLabor_Cost record);
    
    List<ProductLabor_Cost> findProductLabor_Costs(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ProductLabor_Cost> getProductLabor_Costs(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    ProductLabor_Cost getByPid(int pid);
}