package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductBox_In;

public interface ProductBox_InMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_in
     *
     * @mbggenerated Thu Jul 07 14:07:03 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_in
     *
     * @mbggenerated Thu Jul 07 14:07:03 CST 2016
     */
    int insert(ProductBox_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_in
     *
     * @mbggenerated Thu Jul 07 14:07:03 CST 2016
     */
    int insertSelective(ProductBox_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_in
     *
     * @mbggenerated Thu Jul 07 14:07:03 CST 2016
     */
    ProductBox_In selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_in
     *
     * @mbggenerated Thu Jul 07 14:07:03 CST 2016
     */
    int updateByPrimaryKeySelective(ProductBox_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_in
     *
     * @mbggenerated Thu Jul 07 14:07:03 CST 2016
     */
    int updateByPrimaryKey(ProductBox_In record);
    
    List<ProductBox_In> findProductBoxIns(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ProductBox_In> getProductBoxIns(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    List<ProductBox_In> getByPid(int pid);
}