package com.grotek.dao;

import java.util.List;

import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductPack_Store;
import com.grotek.pojo.ProductPage_Store;

public interface ProductPage_StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_store
     *
     * @mbggenerated Mon Jul 04 08:48:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_store
     *
     * @mbggenerated Mon Jul 04 08:48:49 CST 2016
     */
    int insert(ProductPage_Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_store
     *
     * @mbggenerated Mon Jul 04 08:48:49 CST 2016
     */
    int insertSelective(ProductPage_Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_store
     *
     * @mbggenerated Mon Jul 04 08:48:49 CST 2016
     */
    ProductPage_Store selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_store
     *
     * @mbggenerated Mon Jul 04 08:48:49 CST 2016
     */
    int updateByPrimaryKeySelective(ProductPage_Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_store
     *
     * @mbggenerated Mon Jul 04 08:48:49 CST 2016
     */
    int updateByPrimaryKey(ProductPage_Store record);
    
    List<ProductPage_Store> getProductPageStores(PageRequest pageable);
    
    int allCount();
    
    ProductPage_Store getByPid(int pid);
}