package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductPack;
import com.grotek.pojo.ProductRaw;

public interface ProductPackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpackinfo
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpackinfo
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    int insert(ProductPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpackinfo
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    int insertSelective(ProductPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpackinfo
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    ProductPack selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpackinfo
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    int updateByPrimaryKeySelective(ProductPack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpackinfo
     *
     * @mbggenerated Sat Jun 25 11:14:03 CST 2016
     */
    int updateByPrimaryKey(ProductPack record);
    
    List<ProductPack> findProductPacks(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ProductPack> getProductPacks(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    int checkNameAndCode(@Param("name")String name,@Param("code")String code);
}