package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductPack_In;
import com.grotek.pojo.ProductPage_In;

public interface ProductPage_InMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_in
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_in
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    int insert(ProductPage_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_in
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    int insertSelective(ProductPage_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_in
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    ProductPage_In selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_in
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    int updateByPrimaryKeySelective(ProductPage_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_in
     *
     * @mbggenerated Mon Jul 04 09:06:45 CST 2016
     */
    int updateByPrimaryKey(ProductPage_In record);
    
    List<ProductPage_In> findProductPageIns(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ProductPage_In> getProductPageIns(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    List<ProductPage_In> getByPid(int pid);
}