package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductRaw_In;
import com.grotek.pojo.ProductRaw_Price;

public interface ProductRaw_InMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_in
     *
     * @mbggenerated Wed Jun 22 16:56:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_in
     *
     * @mbggenerated Wed Jun 22 16:56:49 CST 2016
     */
    int insert(ProductRaw_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_in
     *
     * @mbggenerated Wed Jun 22 16:56:49 CST 2016
     */
    int insertSelective(ProductRaw_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_in
     *
     * @mbggenerated Wed Jun 22 16:56:49 CST 2016
     */
    ProductRaw_In selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_in
     *
     * @mbggenerated Wed Jun 22 16:56:49 CST 2016
     */
    int updateByPrimaryKeySelective(ProductRaw_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_in
     *
     * @mbggenerated Wed Jun 22 16:56:49 CST 2016
     */
    int updateByPrimaryKey(ProductRaw_In record);
    
    List<ProductRaw_In> findProductRawIns(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ProductRaw_In> getProductRawIns(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    List<ProductRaw_In> getByPid(int pid);
}