package com.grotek.dao;

import java.util.List;

import com.grotek.pojo.ProductPackApItem;
import com.grotek.pojo.ProductboxApItem;

public interface ProductPackApItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_ap_item
     *
     * @mbggenerated Thu Jul 21 11:32:20 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_ap_item
     *
     * @mbggenerated Thu Jul 21 11:32:20 CST 2016
     */
    int insert(ProductPackApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_ap_item
     *
     * @mbggenerated Thu Jul 21 11:32:20 CST 2016
     */
    int insertSelective(ProductPackApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_ap_item
     *
     * @mbggenerated Thu Jul 21 11:32:20 CST 2016
     */
    ProductPackApItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_ap_item
     *
     * @mbggenerated Thu Jul 21 11:32:20 CST 2016
     */
    int updateByPrimaryKeySelective(ProductPackApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_ap_item
     *
     * @mbggenerated Thu Jul 21 11:32:20 CST 2016
     */
    int updateByPrimaryKey(ProductPackApItem record);
    
    List<ProductPackApItem> getByAid(int aid);
    
    List<ProductPackApItem> getByPid(int pid);
}