package com.grotek.dao;

import com.grotek.pojo.ProductBoxInScheme;

public interface ProductBoxInSchemeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productbox_in_scheme
	 * @mbggenerated  Tue Jul 05 10:10:47 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productbox_in_scheme
	 * @mbggenerated  Tue Jul 05 10:10:47 CST 2016
	 */
	int insert(ProductBoxInScheme record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productbox_in_scheme
	 * @mbggenerated  Tue Jul 05 10:10:47 CST 2016
	 */
	int insertSelective(ProductBoxInScheme record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productbox_in_scheme
	 * @mbggenerated  Tue Jul 05 10:10:47 CST 2016
	 */
	ProductBoxInScheme selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productbox_in_scheme
	 * @mbggenerated  Tue Jul 05 10:10:47 CST 2016
	 */
	int updateByPrimaryKeySelective(ProductBoxInScheme record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table productbox_in_scheme
	 * @mbggenerated  Tue Jul 05 10:10:47 CST 2016
	 */
	int updateByPrimaryKey(ProductBoxInScheme record);
	
	ProductBoxInScheme getByPid(int p_id);
	
	int addone(ProductBoxInScheme record);
}