package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductBox_out;

public interface ProductBox_outMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_out
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_out
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    int insert(ProductBox_out record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_out
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    int insertSelective(ProductBox_out record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_out
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    ProductBox_out selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_out
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    int updateByPrimaryKeySelective(ProductBox_out record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_out
     *
     * @mbggenerated Fri Jul 08 09:46:56 CST 2016
     */
    int updateByPrimaryKey(ProductBox_out record);
    
    List<ProductBox_out> findProductBox_outs(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ProductBox_out> getProductBox_outs(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    List<ProductBox_out> getByPid(int pid);
    
    List<ProductBox_out> findProductBox_outsByDid(@Param("did")int did,@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ProductBox_out> getProductBox_outsByDid(@Param("did")int did,@Param("pageable")PageRequest pageable);
    
    int searchCountByDid(@Param("did")int did,@Param("key")String key);
    
    int allCountByDid(int did);
 
}