package com.grotek.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductLabor_Time;

public interface ProductLabor_TimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_time
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_time
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    int insert(ProductLabor_Time record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_time
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    int insertSelective(ProductLabor_Time record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_time
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    ProductLabor_Time selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_time
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    int updateByPrimaryKeySelective(ProductLabor_Time record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productlabor_time
     *
     * @mbggenerated Thu Jul 14 19:52:11 CST 2016
     */
    int updateByPrimaryKey(ProductLabor_Time record);
    
    List<ProductLabor_Time> findProductLabor_Times(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ProductLabor_Time> getProductLabor_Times(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    List<ProductLabor_Time> getByPid(@Param("pid")int pid,@Param("pageable")PageRequest pageable);
    
    List<ProductLabor_Time> getByMonth(@Param("stime")Date stime,@Param("etime")Date etime);
}