package com.grotek.dao;

import java.util.List;

import com.grotek.pojo.ProductboxApItem;

public interface ProductboxApItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_ap_item
     *
     * @mbggenerated Thu Jul 21 10:58:29 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_ap_item
     *
     * @mbggenerated Thu Jul 21 10:58:29 CST 2016
     */
    int insert(ProductboxApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_ap_item
     *
     * @mbggenerated Thu Jul 21 10:58:29 CST 2016
     */
    int insertSelective(ProductboxApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_ap_item
     *
     * @mbggenerated Thu Jul 21 10:58:29 CST 2016
     */
    ProductboxApItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_ap_item
     *
     * @mbggenerated Thu Jul 21 10:58:29 CST 2016
     */
    int updateByPrimaryKeySelective(ProductboxApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_ap_item
     *
     * @mbggenerated Thu Jul 21 10:58:29 CST 2016
     */
    int updateByPrimaryKey(ProductboxApItem record);
    
    List<ProductboxApItem> getByAid(int aid);
    
    List<ProductboxApItem> getByPid(int pid);
}