package com.grotek.dao;

import java.util.List;

import com.grotek.pojo.ProductPageApItem;

public interface ProductPageApItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_ap_item
     *
     * @mbggenerated Thu Jul 21 11:12:24 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_ap_item
     *
     * @mbggenerated Thu Jul 21 11:12:24 CST 2016
     */
    int insert(ProductPageApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_ap_item
     *
     * @mbggenerated Thu Jul 21 11:12:24 CST 2016
     */
    int insertSelective(ProductPageApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_ap_item
     *
     * @mbggenerated Thu Jul 21 11:12:24 CST 2016
     */
    ProductPageApItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_ap_item
     *
     * @mbggenerated Thu Jul 21 11:12:24 CST 2016
     */
    int updateByPrimaryKeySelective(ProductPageApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpage_ap_item
     *
     * @mbggenerated Thu Jul 21 11:12:24 CST 2016
     */
    int updateByPrimaryKey(ProductPageApItem record);
    
    List<ProductPageApItem> getByAid(int aid);
    
    List<ProductPageApItem> getByPid(int pid);
}