package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductRaw_In;
import com.grotek.pojo.ProductRaw_Out;

public interface ProductRaw_OutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_out
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_out
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    int insert(ProductRaw_Out record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_out
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    int insertSelective(ProductRaw_Out record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_out
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    ProductRaw_Out selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_out
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    int updateByPrimaryKeySelective(ProductRaw_Out record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productraw_out
     *
     * @mbggenerated Wed Jun 22 20:42:29 CST 2016
     */
    int updateByPrimaryKey(ProductRaw_Out record);
    
    List<ProductRaw_Out> findProductRawOuts(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ProductRaw_Out> getProductRawOuts(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    List<ProductRaw_Out> getByPid(int pid);
    
    List<ProductRaw_Out> getByBoxinId(int boxinid);
}