package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductPack_In;
import com.grotek.pojo.ProductRaw_In;

public interface ProductPack_InMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_in
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_in
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    int insert(ProductPack_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_in
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    int insertSelective(ProductPack_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_in
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    ProductPack_In selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_in
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    int updateByPrimaryKeySelective(ProductPack_In record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpack_in
     *
     * @mbggenerated Thu Jun 30 14:36:25 CST 2016
     */
    int updateByPrimaryKey(ProductPack_In record);
    
    List<ProductPack_In> findProductPackIns(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ProductPack_In> getProductPackIns(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    List<ProductPack_In> getByPid(int pid);
}