package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductPack;
import com.grotek.pojo.ProductPage;

public interface ProductPageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpageinfo
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpageinfo
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    int insert(ProductPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpageinfo
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    int insertSelective(ProductPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpageinfo
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    ProductPage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpageinfo
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    int updateByPrimaryKeySelective(ProductPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productpageinfo
     *
     * @mbggenerated Fri Jul 01 15:42:21 CST 2016
     */
    int updateByPrimaryKey(ProductPage record);
    
    List<ProductPage> findProductPages(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ProductPage> getProductPages(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    int checkNameAndCode(@Param("name")String name,@Param("code")String code);
}