package com.grotek.dao;

import java.util.List;

import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductBox_Store;
import com.grotek.pojo.ProductRaw_Store;

public interface ProductBox_StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_store
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_store
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    int insert(ProductBox_Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_store
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    int insertSelective(ProductBox_Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_store
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    ProductBox_Store selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_store
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    int updateByPrimaryKeySelective(ProductBox_Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productbox_store
     *
     * @mbggenerated Thu Jul 07 13:46:22 CST 2016
     */
    int updateByPrimaryKey(ProductBox_Store record);
    
    List<ProductBox_Store> getProductBoxStores(PageRequest pageable);
    
    int allCount();
    
    ProductBox_Store getByPid(int pid);
}