package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProjectWork;

public interface ProjectWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectwork
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectwork
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    int insert(ProjectWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectwork
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    int insertSelective(ProjectWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectwork
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    ProjectWork selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectwork
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    int updateByPrimaryKeySelective(ProjectWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projectwork
     *
     * @mbggenerated Mon Jul 18 14:46:14 CST 2016
     */
    int updateByPrimaryKey(ProjectWork record);
    
    List<ProjectWork> getWorksByEid(@Param("eid")String eid,@Param("pageable")PageRequest pageable);
    
    int allCountByEid(String eid);
    
    List<ProjectWork> findWorks(@Param("eid")String eid,@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    int searchCountByEid(@Param("eid")String eid,@Param("key")String key);
    
    List<ProjectWork> getWorksByLeader(@Param("sid")String sid,@Param("pageable")PageRequest pageable);
    
    int allCountBySid(String sid);

}