package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.ProductRaw_Price;
import com.grotek.pojo.ReferencePackWeight;

public interface ReferencePackWeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference_packweight
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference_packweight
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    int insert(ReferencePackWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference_packweight
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    int insertSelective(ReferencePackWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference_packweight
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    ReferencePackWeight selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference_packweight
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    int updateByPrimaryKeySelective(ReferencePackWeight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reference_packweight
     *
     * @mbggenerated Wed Jun 29 14:02:02 CST 2016
     */
    int updateByPrimaryKey(ReferencePackWeight record);
    
    List<ReferencePackWeight> findReferencePackWeights(@Param("key")String key,@Param("pageable")PageRequest pageable);
    
    List<ReferencePackWeight> getReferencePackWeights(PageRequest pageable);
    
    int searchCount(String key);
    
    int allCount();
    
    ReferencePackWeight getByPid(int pid);
}