package com.grotek.dao;

import java.util.List;

import com.grotek.pojo.ReputationDic;

public interface ReputationDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reputation_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reputation_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int insert(ReputationDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reputation_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int insertSelective(ReputationDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reputation_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    ReputationDic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reputation_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int updateByPrimaryKeySelective(ReputationDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reputation_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int updateByPrimaryKey(ReputationDic record);
    
    List<ReputationDic> getAll();
}