package com.grotek.dao;

import com.grotek.pojo.RewardDic;

public interface RewardDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int insert(RewardDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int insertSelective(RewardDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    RewardDic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int updateByPrimaryKeySelective(RewardDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int updateByPrimaryKey(RewardDic record);
}