package com.grotek.dao;

import java.util.List;

import com.grotek.pojo.SampleApItem;

public interface SampleApItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_ap_item
     *
     * @mbggenerated Mon Nov 14 13:15:42 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_ap_item
     *
     * @mbggenerated Mon Nov 14 13:15:42 CST 2016
     */
    int insert(SampleApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_ap_item
     *
     * @mbggenerated Mon Nov 14 13:15:42 CST 2016
     */
    int insertSelective(SampleApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_ap_item
     *
     * @mbggenerated Mon Nov 14 13:15:42 CST 2016
     */
    SampleApItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_ap_item
     *
     * @mbggenerated Mon Nov 14 13:15:42 CST 2016
     */
    int updateByPrimaryKeySelective(SampleApItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample_ap_item
     *
     * @mbggenerated Mon Nov 14 13:15:42 CST 2016
     */
    int updateByPrimaryKey(SampleApItem record);
    
    List<SampleApItem> getByAid(int aid);
    
    List<SampleApItem> getByPid(int pid);
}