package com.grotek.dao;

import java.util.List;

import com.grotek.pojo.ShopTypeDic;

public interface ShopTypeDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int insert(ShopTypeDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int insertSelective(ShopTypeDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    ShopTypeDic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int updateByPrimaryKeySelective(ShopTypeDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoptype_dic
     *
     * @mbggenerated Fri Jun 10 13:57:54 CST 2016
     */
    int updateByPrimaryKey(ShopTypeDic record);
    
    List<ShopTypeDic> getAll();
}