package com.grotek.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.grotek.pojo.JobtypeDic;
import com.grotek.pojo.TravelExsType;

public interface TravelExsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_exs_type
     *
     * @mbggenerated Sun Aug 21 10:32:28 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_exs_type
     *
     * @mbggenerated Sun Aug 21 10:32:28 CST 2016
     */
    int insert(TravelExsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_exs_type
     *
     * @mbggenerated Sun Aug 21 10:32:28 CST 2016
     */
    int insertSelective(TravelExsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_exs_type
     *
     * @mbggenerated Sun Aug 21 10:32:28 CST 2016
     */
    TravelExsType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_exs_type
     *
     * @mbggenerated Sun Aug 21 10:32:28 CST 2016
     */
    int updateByPrimaryKeySelective(TravelExsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_exs_type
     *
     * @mbggenerated Sun Aug 21 10:32:28 CST 2016
     */
    int updateByPrimaryKey(TravelExsType record);
    
    List<TravelExsType> getAll();
    
    int checkName(@Param("name")String name);
}