package com.grotek.dao;

import java.util.List;
import com.grotek.pojo.TravelRbsmItem;

public interface TravelRbsmItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_rbsm_item
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_rbsm_item
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    int insert(TravelRbsmItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_rbsm_item
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    int insertSelective(TravelRbsmItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_rbsm_item
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    TravelRbsmItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_rbsm_item
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    int updateByPrimaryKeySelective(TravelRbsmItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table travel_rbsm_item
     *
     * @mbggenerated Sun Aug 21 14:31:38 CST 2016
     */
    int updateByPrimaryKey(TravelRbsmItem record);
    
    List<TravelRbsmItem> getByPid(int pid);
}