package com.grotek.dao;

import java.util.List;

import com.grotek.pojo.WeeklyItem;

public interface WeeklyItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_item
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_item
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    int insert(WeeklyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_item
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    int insertSelective(WeeklyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_item
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    WeeklyItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_item
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    int updateByPrimaryKeySelective(WeeklyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly_item
     *
     * @mbggenerated Mon Aug 01 14:20:52 CST 2016
     */
    int updateByPrimaryKey(WeeklyItem record);
    
    List<WeeklyItem> getByWid(int wid);
}