package com.grotek.dao;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.PageRequest;

import com.grotek.pojo.Weekly;

public interface WeeklyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    int insert(Weekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    int insertSelective(Weekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    Weekly selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    int updateByPrimaryKeySelective(Weekly record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekly
     *
     * @mbggenerated Mon Aug 01 13:57:09 CST 2016
     */
    int updateByPrimaryKey(Weekly record);
    
    List<Weekly> getWorksByEid(@Param("eid")String eid,@Param("pageable")PageRequest pageable);
    
    int allCountByEid(String eid);
   
    List<Weekly> getWorksByLeader(@Param("sid")String sid,@Param("pageable")PageRequest pageable);
    
    int allCountBySid(String sid);
    
    List<Weekly> getCheckPendingWorks(@Param("sid")String sid,@Param("pageable")PageRequest pageable);
    
    int allCountCheckPending(String sid);
    
    List<Weekly> getCheckedWorks(@Param("sid")String sid,@Param("pageable")PageRequest pageable);
    
    int allCountChecked(String sid);
    
    Weekly getByDate(@Param("eid")String eid,@Param("date")Date date);
    
    List<Weekly> getCheckedByDate(@Param("eid")String eid,@Param("date")Date date);
    
    List<Weekly> getByStartAndEnd(@Param("eid")String eid,@Param("start")Date start,@Param("end")Date end);
    
    List<Weekly> allWorksByEid(@Param("eid")String eid,@Param("pageable")PageRequest pageable);
    
    int allCheckedCountByEid(String eid);
    
    List<Weekly> getACheckPendingWorks(PageRequest pageable);
    
    int allCountACheckPending();
    
    List<Weekly> getACheckedWorks(PageRequest pageable);
    
    int allCountAChecked();
}